### ISSUE TITLE
Integrate Mailchimp

### ISSUE THREAD

**Issue by andmor-** [clarin-eric/clarin-drupal-bootstrap-theme#29]
Mailchimp system is still missing and should be integrated.

**Comment by digitalrebelbv** [comment]
I see Mailchimp is missing in the composer file and that's why it's not there. Can you add it to composer:
`composer require 'drupal/mailchimp:^2.0'`

The styles for the block are already there so when it's added to composer and we enable it (can you also do that and add that to config) then it's good to go.

**Comment by andmor-** [comment]
Mailchimp is now integrated but after signing up in the form, the confirmation message is not being displayed. See #38
