### ISSUE TITLE
Mailchimp confirmation message not showing

### ISSUE THREAD

**Issue by andmor-** [clarin-eric/clarin-drupal-bootstrap-theme#38]
After subscribing for the newsflash in the front page form, a confirmation (or error) message should be displayed. This is currently not working.

**Comment by digitalrebelbv** [comment]
@andmor- this is because the status message block is in a region that is not on the frontpage (Top Bar). If you move it to a region that is displaying it works. FYI: It shows up as a popup box on the right of the screen (see screenshot of it working on my local)
<img width="1141" alt="Screenshot 2021-04-14 at 01 11 51" src="https://user-images.githubusercontent.com/41824433/114632206-7c6a6980-9cbe-11eb-8fa9-44d141ca8eae.png">

If you want it differently you can also make a thank you page and link to that.

**Comment by andmor-** [comment]
Yes it works. Thank you.
